const express = require("express");
const app = express();
const cookies = require("cookie-parser");
const userRoute = require("./../routes/userRoute");
const errorController = require("./../controller/errorController");
const paymeRoute = require("./../routes/paymentRoute");
const viewRoute = require("./../routes/viewRoute");
app.use(express.json());
app.use(express.urlencoded());
app.use(cookies());
app.set("view engine", "pug");
app.set("views", `${__dirname}/../views`);
app.use("/api/v1/users", userRoute);
app.use("/api/v1/payme", paymeRoute);
app.use("/", viewRoute);
app.all("*", function (req, res, next) {
  next(new AppError(`this url has not found: ${req.originalUrl}`, 404));
});
app.use(errorController);
module.exports = app;
